name: tesr run

on:
  push:
    tags: [ "*" ]

jobs:
  build:

    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Print 1
      run: |
        vers=${GITHUB_REF#refs/tags/}
        vers=${vers/rc} 
        echo $vers
    - name: Print 2
      run: echo ${GITHUB_REF#refs/tags/}      
