name: check commit

on:
  push:
    tags: [ "test-*.rc*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Print 1
      run: echo ${GITHUB_REF#refs/tags/}
    - name: Print 2
      run: echo ${GITHUB_REF#refs/tags/test-}
    - name: Print 3
      run: echo ${GITHUB_REF#refs/tags/test-*rc*}
      
